language: go
go:
- 1.5.3
sudo: required
git:
  submodules: false
install:
- sudo pip install Pygments
- go get github.com/spf13/hugo
script: bash ./deploy.sh
after_success:
- rsync -az --force --progress -e "ssh" public/ $TARGETDIR
env:
  global:
    secure: rBudbJm0mGemUI2xuvMpcVPPb0Ga6rSXCBIQiDl29JQAfcy97SJOgmrTNCMmpn8x1pHoNXd+Fa592OYLKZYQ7F22diN8y65opr9okshs7esC10qdZ4wlSWoKvU3VD3vAifS4Yx99qBug4sbDM3Xg5SC61pkMNgNi4K3aUOW9a5E9u0DW0LBOqRoa2x5So/HOorA6YWgDSHZ7GgS/jLN802TJ8vBFplQK6NMrdbw8Uvj241zjRlawroxjMaPxFgj8lPkqlF8ku0bjsBScwzteYfEAvf2/X2On6kWJ5Azn9iUHwC953P2ZYapHJTgqbHxNgwhwwBzwxHgQHXIHJ7CvvOoh6LcbsUSYnlmYqwtw0pUCZe8nkaFr9/QBa5h+2t+Nhg8600PRqrWF8+FBui+aqAZ1lBzbhQ6s/24fd14amD5eqvC+4jhcV6SVOEJEYIzBdl6pA8RF7Q1zft78AAVpzlL0SqEeu1OhnvF881k9CfFiAZHdxDdSjAf/ClkdW66wEn03RgLmyzCo3hfSbPXlFOMy2Lzt74rOlQAIMc2zP9EhbrdGBx1TTtSFdEY32Kgq3oAtyPsfuCTHhLRtpXaYH0FSW9ebo6dXD5WoAeveKeMZ96Dlxeq+xp31k4rSEDJO8GI52vK5lFdxiC74wmdyyhDU8elxSoG3K16ljAu9g/4=
