language: go
go:
- 1.5.3
sudo: required
git:
  submodules: false
install:
- sudo pip install Pygments
- go get github.com/spf13/hugo
script: bash ./deploy.sh
env:
  global:
  - secure: ovwtsjS2CTws5EmJjkRrTLafdM5jPAXVqzqAXzdg0aVVdcG//qOIy9yaxhGxxLpe4aNFqTWlVw3EfcuQY+O4/0mhc9lrxlcUcgo95TXZqhJ+faE/0qc70Nl5q5TD7wJRFvXTu7LHldilo6bcX3kqSrSUPeOPeO1vh1e5W3vwDVRaj1Ti/uaR3OFr/4PO/oCNHwmC0AGJNA7TQX6lMxeu9QpqmGLXhjx4/EeTHckZ05pHzDBG0YE5qqnXKhimTbIQMQjCBkjQ24Y81wtLEybGymuXM/BFn5e+pt2OKyz8Jq/o5NS3Wi0KFITGNi9qXLijkvBt9/jikZr/oaQna735pxhRTpGt31JpVfTtwpCSmOFm7ihM875pmFGq0836EX3zBPHY9tLkaYaMlTiBzIj8mr1GFgxUzt15IyNMzw+Ktg7wVk3/LCvmEUJpHK7diLcYUuF1rTGeS/7Iw+u2aZtZOZ7puKRopfsexHyPy1iVo2+L4Vge92TdMROkYzxoe51hcps/UoiuSHJrSl7hgN9DiF18fMtV6JVVbBCN/NvYLnFHawc+3OrK9SsLIm34uY3Ew1UbrpNx7ylPmfmZKcjZZK/8RizYN+GVe3b196yQrtNi6jmN2ERPlBf8jJsmV8k6cA2NX3IpPNT5/Jc2kROYGgZBu2pnUQVr7gYkCG4NJVw=
  - secure: PHxkpaj2SdS6CyCBxt7v9YZc+k16AfgDgVIXdCKNWmvnUSk5i3TPk+N9H0DEocXvqSXkcY2smLoVHoQNSaJIQ2x7VU427u2gi0D6SR6HMnefXxGUTuWYz8nobU41UYylUPBboLzslBZjFcQ7xs7ncM1Zht/yDWcd2tmdlkJJnKpNVoTXel8Sea3/uN3HMqSPfNbq1bI6T2YxvzOBfpkZZDpMYNkXt/xx8sJ5+Fhwz7i15diWd19PP3isyvpAmyyFMUUhC0wJQEmzzec1dLPXhT/pk24lAGjKhp7RBKoVtSPO4d1v4t0xCuaZRKl+sFirojl/qB85JmScaVFl7WKBfsjd5sU+/Dn+L99uTEAJIYQz4Rj4QncNk1aveXB9HnX/wLbJO8wpFZkTBnUtnqcTlV1pJY/ToJBZR+ksz1baJDcRoqpzHsThTMzFcPyLiWFX3zl8UBLzoJzPBKaLjGVguNheatYbTUGAa0jsvYmrjuqYEeHBsM/CskiESRYLb5NaQdHb8L4WrbeaFq7dKk9nmZYHB+urD0w3rnRdqKueKDAiRCrjbbOS17J+1GVnlebzPQpuKLlWfYzd339whdPnXPhwULY8A1I0+DH+NrDBMdt5eycvkVOqmuyUYwQEd0wZ8C15Nq/QxczTDArcEdGPOVJ5fPiMik29DpvvREuYOeg=
after_success:
  - "rsync -az --force --progress -e "ssh" . $USER:$PASS@jnjosh.webfactional.com:~/tmp"
