baseurl = "/"
languageCode = "en-us"
title = "internet weblog"
theme = "internet-weblog"
googleAnalytics = "UA-17240422-2"
pygmentsstyle = "emacs"
Paginate = 10
SectionPagesMenu = "main"

[author]
	Handle = "jnjosh"
	FirstName = "Josh"
	LastName = "Johnson"
	AboutPage = "/about"
	Location = "Durham, NC"
	FlickrID = "87151163@N00"

[params]
	Description = "Internet weblog of Software (Mac, iOS, Web) Developer, Josh Johnson."
	ShowCopyright = true
	RSSEnabled = true
	RSSSections = [ "Posts", "Microposts", "Photos" ]

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[[menu.main]]
	name = "Posts"
	weight = 1
	identifier = "posts"
	url = "/posts/"

[[menu.main]]
	name = "Microposts"
	weight = 2
	identifier = "microposts"
	url = "/microposts/"

[[menu.main]]
	name = "Photos"
	weight = 3
	identifier = "photos"
	url = "/photos/"
